"""Build original Kook'n research graphic previews from site data. No posts or network.

HTML/CSS artwork is deliberately separate from the publishing queue until reviewed.
Numbers are copied from the same game payload visitors read, never generated by an LLM.
"""
import argparse
import base64
import html
import json
from datetime import datetime, timedelta, timezone
from pathlib import Path
from zoneinfo import ZoneInfo

ROOT = Path(__file__).resolve().parents[1]
EASTERN = ZoneInfo('America/Indiana/Indianapolis')
esc = lambda value: html.escape(str(value))


def when(value):
    return datetime.fromisoformat(value.replace('Z', '+00:00'))


def row(title, detail, badge):
    return f'<div class="row"><div><h3>{esc(title)}</h3><p>{esc(detail)}</p></div><strong>{esc(badge)}</strong></div>'


def build(data, detail, now, logo):
    generated = when(data['generatedAt']).astimezone(EASTERN).strftime('%b %d · %I:%M %p ET')
    start = now.astimezone(EASTERN).date()
    game_name = f"{detail['away']['name']} at {detail['home']['name']}"
    favorites = [r for r in detail.get('favoriteLines', []) if r.get('history') and
                 r['history'].get('last') and r['history']['last']['games'] >= 5 and
                 0 <= (now - when(r['observedAt'])).total_seconds() <= 43200][:5]
    menu = ''.join(row(r['title'],
        f"{r['odds']:+d} {r['book']} · projection {r['projection']:g} · last {r['history']['last']['games']} observed games",
        f"{r['history']['last']['hits']}/{r['history']['last']['games']}") for r in favorites)
    menu = menu or row('No qualifying priced trends', 'We do not shorten the sample to manufacture a streak.', 'PASS')
    scorers = ''.join(row(r['player'],
        f"{r['redZone']} red-zone opportunities · {r['touchdowns']} rushing/receiving TDs · {r['games']}/{r['teamGames']} team games observed",
        f"{r['inside10']} inside 10") for r in detail.get('scorerResearch', []))
    scorers = scorers or row('Not enough verified role history', 'No forced touchdown recommendation.', 'WAIT')
    schedule = []
    for i in range(7):
        day = start + timedelta(days=i)
        games = [g for g in data['games'] if when(g['kickoff']).astimezone(EASTERN).date() == day]
        if not games:
            schedule.append(row(day.strftime('%a · %b %d'), 'No games in this captured schedule', '—'))
        elif len(games) > 3:
            schedule.append(row(day.strftime('%a · %b %d'), f"{len(games)} games · full schedule and research on the site", 'FULL SLATE'))
        else:
            schedule.append(row(day.strftime('%a · %b %d'), ' / '.join(f"{g['away']['abbr']} @ {g['home']['abbr']} {when(g['kickoff']).astimezone(EASTERN):%I:%M %p}" for g in games), 'ET'))
    def card(kind, title, subtitle, body, note, tone):
        return f'<article class="poster {tone}"><header><img src="{logo}" alt="Kook’n chef"><b>KOOK’N</b><span>RESEARCH PREVIEW</span></header><p class="kicker">{kind}</p><h1>{title}</h1><p class="subtitle">{esc(subtitle)}</p><div class="rows">{body}</div><footer><b>{note}</b><p>keenroudy.com/sports · Captured {generated}</p><small>Historical evidence, not guaranteed outcomes. Entertainment only. 21+.</small></footer></article>'
    cards = card('THE MATCHUP MENU', 'Numbers worth<br>a closer look.', game_name, menu,
                 'Main-line research · not additional official plays', 'mint')
    cards += card('END-ZONE RESEARCH', 'Who’s getting<br>the scoring work?', game_name, scorers,
                  'Historical scoring work · verify injuries · no verified TD prices', 'violet')
    cards += card('THE KITCHEN’S OPEN', 'Your week<br>of football.', 'Daily coverage. Never a forced daily bet.', ''.join(schedule),
                  'Times Eastern · verify schedule changes on game day', 'cyan')
    return '''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Kook’n research graphic previews</title><style>
*{box-sizing:border-box}body{margin:0;padding:32px;background:#030911;color:#effaff;font-family:Arial,sans-serif}.gallery{display:flex;gap:28px;align-items:flex-start;flex-wrap:wrap}.poster{--accent:#55edb2;width:540px;min-height:720px;padding:30px;border:1px solid #285568;border-radius:25px;position:relative;overflow:hidden;background:radial-gradient(ellipse at 100% 0%,#14596a88,transparent 55%),linear-gradient(155deg,#0e2235,#080f1b)}.violet{--accent:#c2a2ff;background:radial-gradient(ellipse at 100% 0%,#593d9788,transparent 55%),#0b1322}.cyan{--accent:#6adfff}header{display:flex;align-items:center;gap:10px;letter-spacing:3px;font-size:19px}header img{height:44px;width:44px;border-radius:50%;border:1px solid var(--accent)}header span{margin-left:auto;font-size:10px;letter-spacing:1px;color:#9fb8ca}.kicker{color:var(--accent);font-weight:900;letter-spacing:3px;font-size:12px;margin-top:32px}h1{font-size:43px;letter-spacing:-1.4px;line-height:1.03;margin:14px 0}.subtitle{color:#c0d2de;font-size:15px;min-height:35px}.rows{display:grid;gap:10px;margin-top:25px}.row{display:flex;gap:15px;align-items:center;justify-content:space-between;border:1px solid #344255;border-left:4px solid var(--accent);border-radius:12px;padding:15px;background:#0d1928d9}.row h3{margin:0;font-size:17px}.row p{color:#a8bfcc;margin:7px 0 0;font-size:12px;line-height:1.5}.row strong{flex-shrink:0;color:var(--accent);font-size:19px;max-width:100px;text-align:right}footer{border-top:1px solid #344255;margin-top:26px;padding-top:18px;font-size:12px}footer b{color:var(--accent)}footer p,footer small{color:#9fb7c7}h2{font-size:17px;color:#9fb7c7;margin:0 0 25px}@media(max-width:600px){body{padding:12px}.poster{width:100%;padding:20px}h1{font-size:35px}.row{padding:11px}.row h3{font-size:15px}.row strong{font-size:16px}header span{font-size:8px}}
</style><h2>Original Kook’n concepts · preview only · nothing queued or posted</h2><main class="gallery">''' + cards + '</main></html>'


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--game', required=True)
    parser.add_argument('--out', type=Path, default=ROOT / 'work/research-preview.html')
    args = parser.parse_args()
    data = json.loads((ROOT / 'site/data/app/today.json').read_text())
    detail = json.loads((ROOT / f'site/data/app/games/{args.game}.json').read_text())
    logo = 'data:image/png;base64,' + base64.b64encode((ROOT / 'site/kookn-chef.png').read_bytes()).decode()
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(build(data, detail, datetime.now(timezone.utc), logo))
    print(args.out)
